### ISSUE TITLE
SVGs containing encoded colours get encoded not respecting encode:undefined

### ISSUE THREAD

**Issue by marek-saji** [ben-eb/postcss-svgo#57]
# Steps to reproduce

1. `npm install postcss-cli postcss-svgo`

2. Create `postcss.config.js` with:

     ```js
    module.exports = {
        plugins: [
            require('postcss-svgo')
        ]
    };
    ```

3. Create `foo.css` with:

    ```css
    fff { background-image: url("data:image/svg+xml,<svg><path stroke='#fff' d='M0,0 1'/></svg>"); }
    enc-fff { background-image: url("data:image/svg+xml,<svg><path stroke='%23fff' d='M0,0 1'/></svg>"); }
    white { background-image: url("data:image/svg+xml,<svg><path stroke='white' d='M0,0 1'/></svg>"); }
    ```

4. `./node_modules/.bin/postcss foo.css`

# Expected result

```css
fff { background-image: url('data:image/svg+xml;charset=utf-8,<svg><path stroke="%23fff" d="M0 0l1 NaN"/></svg>'); }
enc-fff { background-image: url('data:image/svg+xml;charset=utf-8,<svg><path stroke="%23fff" d="M0 0l1 NaN"/></svg>'); }
white { background-image: url('data:image/svg+xml;charset=utf-8,<svg><path stroke="%23fff" d="M0 0l1 NaN"/></svg>'); }
```

[`encode` option](https://github.com/ben-eb/postcss-svgo/blob/d65b837ba2baae3082f4ea331740bc9b7c9f00f0/README.md#encode) is not set, so only `#` should get encoded.

# Result

```css
fff { background-image: url('data:image/svg+xml;charset=utf-8,<svg><path stroke="%23fff" d="M0 0l1 NaN"/></svg>'); }
enc-fff { background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%3E%3Cpath stroke='%23fff' d='M0 0l1 NaN'/%3E%3C/svg%3E"); }
white { background-image: url('data:image/svg+xml;charset=utf-8,<svg><path stroke="%23fff" d="M0 0l1 NaN"/></svg>'); }
```

Whole inlinded SVG containing already encoded colour gets encoded.
